export interface Mentor {
  id: string;
  name: string;
  role: string;
  company: string;
  location: string;
  countryCode: string;
  price: number;
  rating: number;
  reviewsCount: number;
  bio: string;
  fullBio: string;
  specialties: string[];
  helpTopics: string[];
  languages: string[];
  isVerified: boolean;
  avatarColor: string;
  nextAvailable: string;
}

export const mentors: Mentor[] = [
  {
    id: "m1",
    name: "Sarah Mitchell",
    role: "Senior Software Engineer",
    company: "Google",
    location: "USA",
    countryCode: "🇺🇸",
    price: 45,
    rating: 4.9,
    reviewsCount: 124,
    bio: "Ex-Meta, current Google SWE. Helping you break into FAANG.",
    fullBio: "I have over 8 years of experience in the tech industry, having worked at Meta and now Google. I specialize in backend systems and interview preparation. I've conducted over 100 technical interviews and know exactly what hiring managers are looking for. Let's get you that offer!",
    specialties: ["Full Stack", "Career Transitions", "FAANG Prep"],
    helpTopics: ["Mock Interviews", "Resume Review", "System Design", "Salary Negotiation"],
    languages: ["English"],
    isVerified: true,
    avatarColor: "bg-blue-500",
    nextAvailable: "Available Tomorrow 3:00 PM"
  },
  {
    id: "m2",
    name: "Ahmed Al-Farsi",
    role: "Product Manager",
    company: "Microsoft",
    location: "UAE",
    countryCode: "🇦🇪",
    price: 35,
    rating: 4.8,
    reviewsCount: 89,
    bio: "Product strategist passionate about bridging tech and business.",
    fullBio: "With a background in computer science and an MBA, I transitioned into Product Management 5 years ago. I help engineers transition into PM roles and guide students on the best paths to enter the tech industry from a non-coding perspective.",
    specialties: ["Product Strategy", "Tech Careers", "MBA Guidance"],
    helpTopics: ["PM Mock Interviews", "Product Sense", "Transition to PM", "MBA Applications"],
    languages: ["English", "Arabic"],
    isVerified: true,
    avatarColor: "bg-green-500",
    nextAvailable: "Available Friday 10:00 AM"
  },
  {
    id: "m3",
    name: "Dr. Priya Sharma",
    role: "Data Science Lead",
    company: "Amazon",
    location: "India",
    countryCode: "🇮🇳",
    price: 50,
    rating: 5.0,
    reviewsCount: 156,
    bio: "PhD in Machine Learning. Building scalable AI solutions at Amazon.",
    fullBio: "I lead a team of data scientists at Amazon working on recommendation systems. I love mentoring aspiring data scientists, helping them understand what industry actually needs vs what is taught in academia.",
    specialties: ["Data Science", "ML", "Python", "Statistics"],
    helpTopics: ["Portfolio Review", "ML Concepts", "Data Science Interviews", "PhD vs Industry"],
    languages: ["English", "Hindi"],
    isVerified: true,
    avatarColor: "bg-purple-500",
    nextAvailable: "Available Today 6:00 PM"
  },
  {
    id: "m4",
    name: "James Okonkwo",
    role: "Startup Founder",
    company: "Self-Employed (2 Exits)",
    location: "Nigeria",
    countryCode: "🇳🇬",
    price: 60,
    rating: 4.9,
    reviewsCount: 210,
    bio: "Serial entrepreneur. Bootstrapped to $5M ARR and successfully exited twice.",
    fullBio: "I've built, scaled, and sold two SaaS startups. Now, I invest and advise early-stage founders. I can help you validate your idea, figure out your go-to-market strategy, or navigate the fundraising landscape.",
    specialties: ["Entrepreneurship", "Fundraising", "Business Strategy"],
    helpTopics: ["Pitch Deck Review", "Idea Validation", "Growth Strategies", "Investor Relations"],
    languages: ["English", "Igbo"],
    isVerified: true,
    avatarColor: "bg-amber-500",
    nextAvailable: "Available Monday 2:00 PM"
  },
  {
    id: "m5",
    name: "Maria Rodriguez",
    role: "UX Design Director",
    company: "Adobe",
    location: "Spain",
    countryCode: "🇪🇸",
    price: 40,
    rating: 4.8,
    reviewsCount: 92,
    bio: "10+ years crafting digital experiences. Helping designers level up.",
    fullBio: "I'm a design leader passionate about human-centered design. I've reviewed thousands of portfolios and hired dozens of designers. I can help you craft a portfolio that stands out and prepare for whiteboarding challenges.",
    specialties: ["UI/UX", "Design Career", "Portfolio Review"],
    helpTopics: ["Portfolio Feedback", "Case Study Review", "Design Exercises", "Career Pathing"],
    languages: ["English", "Spanish"],
    isVerified: true,
    avatarColor: "bg-rose-500",
    nextAvailable: "Available Wednesday 11:00 AM"
  },
  {
    id: "m6",
    name: "Dr. Khalid Hassan",
    role: "Medical Consultant",
    company: "King Faisal Hospital",
    location: "Saudi Arabia",
    countryCode: "🇸🇦",
    price: 55,
    rating: 4.7,
    reviewsCount: 64,
    bio: "Internal Medicine Consultant guiding future doctors through the medical maze.",
    fullBio: "Navigating medical school and residency matches can be daunting. Having completed my training and USMLE steps successfully, I mentor medical students globally to help them secure competitive residencies.",
    specialties: ["Medical Career", "USMLE", "Residency Applications"],
    helpTopics: ["Personal Statement Review", "Interview Prep (MMI)", "Study Strategies", "Career Planning"],
    languages: ["English", "Arabic"],
    isVerified: true,
    avatarColor: "bg-teal-500",
    nextAvailable: "Available Sunday 8:00 PM"
  },
  {
    id: "m7",
    name: "Emma Thompson",
    role: "HR Director",
    company: "Unilever",
    location: "UK",
    countryCode: "🇬🇧",
    price: 38,
    rating: 4.9,
    reviewsCount: 178,
    bio: "Insider knowledge on what recruiters actually look for in candidates.",
    fullBio: "With 15 years in global HR, I know exactly how applicant tracking systems work and what makes a candidate memorable. I specialize in helping candidates pivot careers or land senior roles through strategic positioning.",
    specialties: ["Job Search", "CV Review", "Interview Skills"],
    helpTopics: ["Resume Optimization", "Mock Behavioral Interviews", "Salary Negotiation", "LinkedIn Branding"],
    languages: ["English"],
    isVerified: true,
    avatarColor: "bg-pink-500",
    nextAvailable: "Available Tomorrow 9:00 AM"
  },
  {
    id: "m8",
    name: "Chen Wei",
    role: "Cybersecurity Expert",
    company: "IBM",
    location: "Singapore",
    countryCode: "🇸🇬",
    price: 48,
    rating: 4.8,
    reviewsCount: 81,
    bio: "Securing the cloud. Helping you break into infosec without a traditional degree.",
    fullBio: "I transitioned into cybersecurity from a non-tech background. I hold CISSP, OSCP, and CEH certifications. I can help you map out the most efficient certification path and build practical skills to land your first infosec role.",
    specialties: ["Cybersecurity", "Certifications", "Ethical Hacking"],
    helpTopics: ["Certification Roadmap", "CTF Guidance", "Resume Review", "Career Pivot"],
    languages: ["English", "Mandarin"],
    isVerified: true,
    avatarColor: "bg-indigo-500",
    nextAvailable: "Available Thursday 4:00 PM"
  },
  {
    id: "m9",
    name: "Fatima Al-Hassan",
    role: "Investment Banking Analyst",
    company: "QNB",
    location: "Qatar",
    countryCode: "🇶🇦",
    price: 42,
    rating: 4.7,
    reviewsCount: 55,
    bio: "Demystifying high finance and helping students break into investment banking.",
    fullBio: "I successfully navigated the highly competitive recruitment process for investment banking. I offer practical advice on networking, financial modeling tests, and surviving the intense interview superdays.",
    specialties: ["Finance Careers", "CFA Prep", "Investment Banking"],
    helpTopics: ["Financial Modeling", "Superday Prep", "Networking Strategies", "CFA Guidance"],
    languages: ["English", "Arabic"],
    isVerified: true,
    avatarColor: "bg-orange-500",
    nextAvailable: "Available Saturday 1:00 PM"
  },
  {
    id: "m10",
    name: "David Park",
    role: "Full Stack Developer",
    company: "Freelance",
    location: "Canada",
    countryCode: "🇨🇦",
    price: 30,
    rating: 4.9,
    reviewsCount: 240,
    bio: "Self-taught dev who built a 6-figure freelance business. I help juniors level up.",
    fullBio: "I taught myself to code and built a successful freelance career on Upwork. I specialize in helping junior developers break out of tutorial hell, build real-world projects, and land their first freelance clients or full-time roles.",
    specialties: ["Web Dev", "Freelancing", "Junior Developers"],
    helpTopics: ["Code Review", "Portfolio Projects", "Freelance Strategy", "Upwork Profile Review"],
    languages: ["English", "Korean"],
    isVerified: true,
    avatarColor: "bg-cyan-500",
    nextAvailable: "Available Today 4:00 PM"
  },
  {
    id: "m11",
    name: "Aisha Malik",
    role: "Digital Marketing Manager",
    company: "Ogilvy",
    location: "Pakistan",
    countryCode: "🇵🇰",
    price: 25,
    rating: 4.8,
    reviewsCount: 112,
    bio: "Growth marketer specializing in organic and paid acquisition strategies.",
    fullBio: "I manage multi-million dollar ad budgets and direct SEO strategies. Whether you want to start a marketing agency, become a freelancer, or land a corporate marketing role, I can guide you on the exact skills you need.",
    specialties: ["SEO", "Social Media", "Content Marketing"],
    helpTopics: ["Campaign Review", "Agency Scaling", "Marketing Resume", "Skill Development"],
    languages: ["English", "Urdu"],
    isVerified: true,
    avatarColor: "bg-fuchsia-500",
    nextAvailable: "Available Tomorrow 5:00 PM"
  },
  {
    id: "m12",
    name: "Robert Kim",
    role: "AI/ML Researcher",
    company: "Stanford University",
    location: "USA",
    countryCode: "🇺🇸",
    price: 70,
    rating: 4.9,
    reviewsCount: 45,
    bio: "Publishing at top AI conferences (NeurIPS, ICML). PhD admission guide.",
    fullBio: "I am a PhD candidate researching Large Language Models. I help students navigate the competitive grad school admissions process, craft compelling Statements of Purpose, and get started in AI research.",
    specialties: ["AI Research", "PhD Guidance", "Machine Learning"],
    helpTopics: ["Grad School Apps", "SOP Review", "Research Ideas", "Paper Feedback"],
    languages: ["English"],
    isVerified: true,
    avatarColor: "bg-sky-500",
    nextAvailable: "Available Monday 10:00 AM"
  }
];
